### ISSUE TITLE
Pokemon Centre Infinite Loop

### ISSUE THREAD

**Issue by Ravendwyr** [Bratmon/FREComboRandomizer#1]
Good evening! I found this a few days ago and decided to give it a try.

I began a new game using `NewGame(16121986)` and the door to the rival's house in Palette Town took me to the Pokemon Centre on Four Island where, being the fool that I am, spoke to the Nurse NPC with no Pokemon and the game got stuck in an infinite loop.

![image](https://user-images.githubusercontent.com/8914/224152799-7f5e28ee-405a-430d-b269-f000d0855784.png)

Did I use an invalid seed? Or does this door need to have some protection like the rival's house in Emerald?

If you need further info let me know. Apologies for any trouble.

**Comment by Bratmon** [comment]
Being able to screw yourself that way is intentional, because I think it's funny.  The rival's house is needed to start the game in Emerald but not Fire Red, so I left it randomized in Fire Red.

If you haven't gotten far enough to get any Pokemon, you can just start over without too much trouble.

**Comment by Ravendwyr** [comment]
Ah ok, that makes sense. I also found this funny but wasn't sure if this was something you needed to know about. Thankfully this was a test run that I was mucking about in and nothing was lost. I'll be more careful in future runs.
